# -*- coding: utf-8 -*-

# mail
mail_host : 'smtp.163.com'
mail_user : 'itsmartkit'
mail_pass : ''
sender : 'itsmartkit@163.com'

# server
getip_url : 'http://www.itsmartkit.com/ip.php'
server_ip : '39.95.20.xxx'
server_port : 12306

# 自动识别验证码
auto_captcha : True

# 是否启用webdriver
enable_webdriver : True

captcha_mode : 'local'#local/net

captcha_path : 'captcha.jpg'

# 真实主机 ip
real_host : '61.147.226.185'

# system
encoding : 'utf-8'

sys_name : 'PABS'

log_path : 'log/logging.log'

# 是否检查休息时间 默认：True
check_sleep_time : True

# 是否核心抢票模式 默认：False, 且建议 False
is_core : False
# 核心模式请求间隔时间，单位s
core_sleep_base : 3
# 任务获取方式
task_src : 'local' #local/net
# 请求缓存路径
req_cache_path : 'cache/req.cache'
# algID缓存路径
algID_cache_path : 'cache/algID.cache'
# 订票信息文件
booking_filename: 'config/booking.yaml'

net_booking_filename: 'config/net_booking.yaml'

# 小黑屋时间，单位s
ticket_black_list_time : 180 
# 保活任务，单位s
keep_alive_time : 2 
# 所抢车次发车前预留最小空余时间，单位min
free_time : 80 
# 相邻两次请求间隔时间，单位s
sleep_base : 1
# 定时任务执行周期
timespan : 1
# 是否循环播放音乐 True/False, 默认：False
loop_play : False
# 结束任务通知音乐
finish_task_audio : 'audio/HeartsDesire.mp3'
# 邮件发送失败通知音乐
post_failed_audio : 'audio/Lively.mp3'